### ISSUE TITLE
Error ADO pipelines 

### ISSUE THREAD

**Issue by vincentcastagna** [jonathanpeppers/boots#16]
Hello,

We installed boots on our Microsoft Pipelines, installation of the extension is ok, but when it comes to install a specific version of Xamarin, here Xamarin Android 9.4, job failes and exit with  follow error and stack trace : 

**Task :** 

  ```
  - task: Boots@1
      displayName: 'Install Xamarin.Android 9.4'
      condition: eq(variables['BuildPlatform'], 'Android')
      inputs:
        uri: 'https://aka.ms/xamarin-android-commercial-d16-2-windows'

```

```
An extension with a matching Identifier is already installed to this product.
2019-10-01T12:45:13.2005148Z 10/1/2019 12:45:11 PM - Microsoft.VisualStudio.ExtensionManager.AlreadyInstalledException: This extension is already installed to all applicable products.
2019-10-01T12:45:13.2005438Z    at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
2019-10-01T12:45:13.2005701Z    at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
2019-10-01T12:45:13.2005982Z    at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
2019-10-01T12:45:13.2006203Z    at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
2019-10-01T12:45:13.2006444Z    at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
2019-10-01T12:45:13.2007062Z    at VSIXInstaller.App.OnStartup(StartupEventArgs e)
2019-10-01T12:45:13.2007438Z --- End of stack trace from previous location where exception was thrown ---
2019-10-01T12:45:13.2007804Z    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
2019-10-01T12:45:13.2008015Z Deleting C:\Users\VssAdministrator\AppData\Local\Temp\dmqo21dp.3n5.vsix

Unhandled Exception: System.Exception: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller.exe' with arguments '/quiet /logFile:C:\Users\VssAdministrator\AppData\Local\Temp\tmp51CC.tmp "C:\Users\VssAdministrator\AppData\Local\Temp\dmqo21dp.3n5.vsix"' exited with code 1001
2019-10-01T12:45:14.0116244Z    at Boots.Core.AsyncProcess.RunAsync(CancellationToken token) in /Users/vsts/agent/2.154.3/work/1/s/Boots.Core/AsyncProcess.cs:line 69
2019-10-01T12:45:14.0117289Z    at Boots.Core.VsixInstaller.Install(String file, CancellationToken token) in /Users/vsts/agent/2.154.3/work/1/s/Boots.Core/VsixInstaller.cs:line 32
2019-10-01T12:45:14.0117901Z    at Boots.Core.VsixInstaller.Install(String file, CancellationToken token) in /Users/vsts/agent/2.154.3/work/1/s/Boots.Core/VsixInstaller.cs:line 35
2019-10-01T12:45:14.0118664Z    at Boots.Core.Bootstrapper.Install(CancellationToken token) in /Users/vsts/agent/2.154.3/work/1/s/Boots.Core/Bootstrapper.cs:line 31
2019-10-01T12:45:14.0119476Z    at Boots.Program.Main(String[] args) in /Users/vsts/agent/2.154.3/work/1/s/Boots/Program.cs:line 24
2019-10-01T12:45:14.0120555Z    at Boots.Program.<Main>(String[] args)
2019-10-01T12:45:14.0659619Z ##[error]The process 'D:\a\_temp\boots-tool\boots.exe' failed with exit code 3762504530
2019-10-01T12:45:14.0670869Z ##[section]Finishing: Install Xamarin.Android 9.4
```
EDIT : @jonathanpeppers

**Comment by jonathanpeppers** [comment]
The full log from `vsixinstaller.exe` should be right before that, what does it say?

Unfortunately, you cannot _downgrade_ a vsix to a version lower than the original installed by the Visual Studio Installer. You could either a) use the 2017 pool or b) use the Mac pool? On Mac pkgs can downgrade just fine.

**Comment by jonathanpeppers** [comment]
Closing for now, let me know if you need something else, thanks!
